
tester:
	gcc stat_tester.c -o stat_tester
	
app:
	$(CC) statistics_app.c -o statistics
	
target:
	echo "Not yet specified!"
	
clean:
	rm statistics.csv statistics_app stat_tester
	
hello:
	$(CC) hello.c -o hello